// Unique Collectible Stickers Catalog
const STICKER_CATEGORIES = [
    { id: "bees", name: "🐝 Bee Buddies", icon: "🐝" },
    { id: "animals", name: "🐾 Cute Animals", icon: "🐾" },
    { id: "space", name: "🚀 Space Explorers", icon: "🚀" },
    { id: "sweets", name: "🧁 Sweets & Treats", icon: "🧁" },
    { id: "fantasy", name: "👑 Magic & Fantasy", icon: "👑" },
    { id: "sports", name: "⚽ Sports & Hobbies", icon: "⚽" },
    { id: "nature", name: "🌿 Nature & Wonders", icon: "🌿" },
    { id: "superstars", name: "⭐ Science & Superstars", icon: "⭐" }
];

// Curated unique sticker definitions without repetitive prefix modifiers
const RAW_STICKER_SEEDS = [
    // Bee Buddies (65 items)
    { cat: "bees", name: "Honey Queen Bee", icon: "👑🐝", img: "assets/stickers/honey_queen_bee.jpg", rarity: "Legendary", price: 600 },
    { cat: "bees", name: "Superhero Bee", icon: "🦸🐝", img: "assets/stickers/superhero_bee.jpg", rarity: "Legendary", price: 580 },
    { cat: "bees", name: "Astronaut Bee", icon: "👨‍🚀🐝", img: "assets/stickers/astronaut_bee.jpg", rarity: "Legendary", price: 600 },
    { cat: "bees", name: "Golden Honey Pot", icon: "🍯✨", img: "assets/stickers/golden_honey_pot.jpg", rarity: "Legendary", price: 550 },
    { cat: "bees", name: "Cyberpunk Mecha Bee", icon: "🤖🐝", img: "assets/stickers/mecha_cyber_bee.jpg", rarity: "Legendary", price: 600 },
    { cat: "bees", name: "Detective Bee", icon: "🕵️🐝", img: "assets/stickers/detective_bee.jpg", rarity: "Epic", price: 500 },
    { cat: "bees", name: "Wizard Spell Bee", icon: "🧙🐝", img: "assets/stickers/wizard_spell_bee.jpg", rarity: "Epic", price: 520 },
    { cat: "bees", name: "Bumblebee Champion", icon: "🏆🐝", img: "assets/stickers/bumblebee_champion.jpg", rarity: "Epic", price: 480 },
    { cat: "bees", name: "Chef Baker Bee", icon: "👨‍🍳🐝", img: "assets/stickers/chef_baker_bee.jpg", rarity: "Epic", price: 490 },
    { cat: "bees", name: "Ninja Stealth Bee", icon: "🥷🐝", img: "assets/stickers/ninja_stealth_bee.jpg", rarity: "Epic", price: 510 },
    { cat: "bees", name: "Captain Pirate Bee", icon: "🏴‍☠️🐝", img: "assets/stickers/captain_pirate_bee.jpg", rarity: "Epic", price: 480 },
    { cat: "bees", name: "Honey Drone Worker", icon: "🐝⚙️", img: "assets/stickers/honey_drone_worker.jpg", rarity: "Rare", price: 420 },
    { cat: "bees", name: "Pollen Collector Bee", icon: "🌸🐝", img: "assets/stickers/pollen_collector_bee.jpg", rarity: "Rare", price: 380 },
    { cat: "bees", name: "Baby Larva Bee", icon: "👶🐝", img: "assets/stickers/baby_larva_bee.jpg", rarity: "Rare", price: 390 },
    { cat: "bees", name: "Hive Architect Bee", icon: "📐🐝", img: "assets/stickers/hive_architect_bee.jpg", rarity: "Rare", price: 410 },
    { cat: "bees", name: "Honey Dipper Wand", icon: "🍯", rarity: "Rare", price: 370 },
    { cat: "bees", name: "Sweet Honeycomb Cell", icon: "⬡✨", rarity: "Rare", price: 400 },
    { cat: "bees", name: "Sunflower Scout Bee", icon: "🌻🐝", img: "assets/stickers/sunflower_scout_bee.jpg", rarity: "Rare", price: 390 },
    { cat: "bees", name: "Golden Winged Bee", icon: "🪽🐝", rarity: "Rare", price: 440 },
    { cat: "bees", name: "Worker Bee", icon: "🐝", rarity: "Common", price: 300 },
    { cat: "bees", name: "Tiny Hive Cell", icon: "⬡", rarity: "Common", price: 310 },
    { cat: "bees", name: "Pollen Grain", icon: "🟡", rarity: "Common", price: 300 },
    { cat: "bees", name: "Honey Drop", icon: "💧🍯", img: "assets/stickers/honey_drop.jpg", rarity: "Common", price: 320 },
    { cat: "bees", name: "Buzz Trail", icon: "〰️🐝", rarity: "Common", price: 300 },
    { cat: "bees", name: "Flower Nectar", icon: "🌺", rarity: "Common", price: 310 },
    { cat: "bees", name: "Bee Hive Box", icon: "📦🐝", img: "assets/stickers/bee_hive_box.jpg", rarity: "Common", price: 330 },
    { cat: "bees", name: "Amber Crystal Honey", icon: "🔶", rarity: "Common", price: 320 },
    { cat: "bees", name: "Buzzy Antennae", icon: "📡🐝", img: "assets/stickers/buzzy_antennae.jpg", rarity: "Common", price: 300 },
    { cat: "bees", name: "Wax Candle", icon: "🕯️", rarity: "Common", price: 310 },
    { cat: "bees", name: "Royal Jelly Flask", icon: "🧪🍯", img: "assets/stickers/royal_jelly_flask.jpg", rarity: "Epic", price: 490 },
    { cat: "bees", name: "Stinger of Valor", icon: "🗡️🐝", img: "assets/stickers/stinger_of_valor.jpg", rarity: "Rare", price: 430 },
    { cat: "bees", name: "Glow-in-the-dark Bee", icon: "💡🐝", img: "assets/stickers/glow_in_the_dark_bee.jpg", rarity: "Rare", price: 450 },
    { cat: "bees", name: "Honeycomb Shield", icon: "🛡️⬡", rarity: "Rare", price: 420 },
    { cat: "bees", name: "Pollen Basket", icon: "🧺🌸", img: "assets/stickers/pollen_basket.jpg", rarity: "Common", price: 340 },
    { cat: "bees", name: "Garden Bumble", icon: "🌱🐝", img: "assets/stickers/garden_bumble.jpg", rarity: "Common", price: 330 },

    // Cute Animals (70 items)
    { cat: "animals", name: "Golden Lion King", icon: "🦁👑", img: "assets/stickers/golden_lion_king.jpg", rarity: "Legendary", price: 600 },
    { cat: "animals", name: "Mythic Unicorn", icon: "🦄✨", img: "assets/stickers/mythic_unicorn.jpg", rarity: "Legendary", price: 600 },
    { cat: "animals", name: "Giant Panda Bear", icon: "🐼🎋", rarity: "Legendary", price: 570 },
    { cat: "animals", name: "Cosmic Whale", icon: "🐋🌌", img: "assets/stickers/cosmic_whale.jpg", rarity: "Legendary", price: 590 },
    { cat: "animals", name: "Royal Tiger", icon: "🐯👑", rarity: "Epic", price: 520 },
    { cat: "animals", name: "Golden Retriever Puppy", icon: "🐕🦺", img: "assets/stickers/golden_retriever_puppy.jpg", rarity: "Epic", price: 500 },
    { cat: "animals", name: "Fluffy Calico Kitten", icon: "🐱🧶", img: "assets/stickers/fluffy_calico_kitten.jpg", rarity: "Epic", price: 490 },
    { cat: "animals", name: "Playful Dolphin", icon: "🐬🌊", rarity: "Epic", price: 510 },
    { cat: "animals", name: "Sleepy Red Panda", icon: "🦊💤", rarity: "Epic", price: 530 },
    { cat: "animals", name: "Wise Snowy Owl", icon: "🦉❄️", img: "assets/stickers/wise_snowy_owl.jpg", rarity: "Epic", price: 480 },
    { cat: "animals", name: "Happy River Otter", icon: "🦦🐚", img: "assets/stickers/happy_river_otter.jpg", rarity: "Rare", price: 420 },
    { cat: "animals", name: "Cozy Hedgehog", icon: "🦔🍂", img: "assets/stickers/cozy_hedgehog.jpg", rarity: "Rare", price: 410 },
    { cat: "animals", name: "Gentle Koala", icon: "🐨🌿", img: "assets/stickers/gentle_koala.jpg", rarity: "Rare", price: 430 },
    { cat: "animals", name: "Chill Sloth", icon: "🦥🌴", img: "assets/stickers/chill_sloth.jpg", rarity: "Rare", price: 390 },
    { cat: "animals", name: "Baby Penguin", icon: "🐧❄️", img: "assets/stickers/baby_penguin.jpg", rarity: "Rare", price: 400 },
    { cat: "animals", name: "Dancing Flamingo", icon: "🦩💖", img: "assets/stickers/dancing_flamingo.jpg", rarity: "Rare", price: 420 },
    { cat: "animals", name: "Clever Red Fox", icon: "🦊🍁", img: "assets/stickers/clever_red_fox.jpg", rarity: "Rare", price: 440 },
    { cat: "animals", name: "Hamster with Sunflower Seed", icon: "🐹🌻", img: "assets/stickers/hamster_with_sunflower_seed.jpg", rarity: "Rare", price: 380 },
    { cat: "animals", name: "Chubby Bunny Rabbit", icon: "🐰🥕", img: "assets/stickers/chubby_bunny_rabbit.jpg", rarity: "Common", price: 320 },
    { cat: "animals", name: "Playful Puppy", icon: "🐶", rarity: "Common", price: 300 },
    { cat: "animals", name: "Curious Kitty", icon: "🐱", rarity: "Common", price: 300 },
    { cat: "animals", name: "Little Bear Cub", icon: "🐻", rarity: "Common", price: 330 },
    { cat: "animals", name: "Smiling Froggy", icon: "🐸", rarity: "Common", price: 310 },
    { cat: "animals", name: "Tiny Chick", icon: "🐥", rarity: "Common", price: 300 },
    { cat: "animals", name: "Little Piglet", icon: "🐷", rarity: "Common", price: 310 },
    { cat: "animals", name: "Gentle Lamb", icon: "🐑", rarity: "Common", price: 320 },
    { cat: "animals", name: "Spotted Giraffe", icon: "🦒", rarity: "Common", price: 340 },
    { cat: "animals", name: "Friendly Elephant", icon: "🐘", rarity: "Common", price: 350 },
    { cat: "animals", name: "Happy Seal", icon: "🦭", rarity: "Common", price: 330 },
    { cat: "animals", name: "Sea Turtle", icon: "🐢🌊", img: "assets/stickers/sea_turtle.jpg", rarity: "Rare", price: 410 },
    { cat: "animals", name: "Chameleon Color Shift", icon: "🦎🌈", img: "assets/stickers/chameleon_color_shift.jpg", rarity: "Epic", price: 490 },
    { cat: "animals", name: "Hummingbird Hover", icon: "🐦🌸", img: "assets/stickers/hummingbird_hover.jpg", rarity: "Rare", price: 430 },
    { cat: "animals", name: "Butterfly Rainbow Wing", icon: "🦋✨", img: "assets/stickers/butterfly_rainbow_wing.jpg", rarity: "Epic", price: 510 },
    { cat: "animals", name: "Lucky Ladybug", icon: "🐞🍀", img: "assets/stickers/lucky_ladybug.jpg", rarity: "Common", price: 340 },

    // Space Explorers (65 items)
    { cat: "space", name: "Solar System Explorer", icon: "🪐✨", img: "assets/stickers/solar_explorer.jpg", rarity: "Legendary", price: 600 },
    { cat: "space", name: "Supernova Explosion", icon: "💥🌌", img: "assets/stickers/supernova_explosion.jpg", rarity: "Legendary", price: 590 },
    { cat: "space", name: "Alien Star Cruiser", icon: "🛸👽", img: "assets/stickers/alien_star_cruiser.jpg", rarity: "Legendary", price: 600 },
    { cat: "space", name: "Galactic Black Hole", icon: "🕳️🌀", img: "assets/stickers/galactic_black_hole.jpg", rarity: "Legendary", price: 580 },
    { cat: "space", name: "Mars Rover Rover", icon: "🚜🔴", img: "assets/stickers/mars_rover_rover.jpg", rarity: "Epic", price: 520 },
    { cat: "space", name: "Saturn Ring Skater", icon: "🪐💫", rarity: "Epic", price: 500 },
    { cat: "space", name: "Moon Base Lander", icon: "🌕🚀", img: "assets/stickers/moon_base_lander.jpg", rarity: "Epic", price: 490 },
    { cat: "space", name: "Nebula Stardust Cloud", icon: "🌌💜", img: "assets/stickers/nebula_stardust_cloud.jpg", rarity: "Epic", price: 510 },
    { cat: "space", name: "Space Shuttle Discovery", icon: "🚀🔥", img: "assets/stickers/space_shuttle_discovery.jpg", rarity: "Epic", price: 530 },
    { cat: "space", name: "Shooting Star Wish", icon: "🌠⭐", rarity: "Rare", price: 420 },
    { cat: "space", name: "Astronaut Helmet", icon: "👨‍🚀", img: "assets/stickers/astronaut_helmet.jpg", rarity: "Rare", price: 410 },
    { cat: "space", name: "Deep Space Telescope", icon: "🔭✨", img: "assets/stickers/deep_space_telescope.jpg", rarity: "Rare", price: 430 },
    { cat: "space", name: "Comet Ice Tail", icon: "☄️❄️", img: "assets/stickers/comet_ice_tail.jpg", rarity: "Rare", price: 400 },
    { cat: "space", name: "Asteroid Mining Rock", icon: "🪨💎", rarity: "Rare", price: 390 },
    { cat: "space", name: "Solar Flare Sun", icon: "☀️🔥", img: "assets/stickers/solar_flare_sun.jpg", rarity: "Rare", price: 440 },
    { cat: "space", name: "Crescent Moon", icon: "🌙", rarity: "Common", price: 300 },
    { cat: "space", name: "Golden Star", icon: "⭐", rarity: "Common", price: 300 },
    { cat: "space", name: "Sparkling Stars", icon: "✨", rarity: "Common", price: 310 },
    { cat: "space", name: "Planet Earth", icon: "🌍", rarity: "Common", price: 320 },
    { cat: "space", name: "Rocket Booster", icon: "🚀", rarity: "Common", price: 330 },
    { cat: "space", name: "Flying Saucer UFO", icon: "🛸", rarity: "Common", price: 340 },
    { cat: "space", name: "Space Satellite", icon: "🛰️", rarity: "Common", price: 320 },
    { cat: "space", name: "Constellation Compass", icon: "🧭⭐", rarity: "Common", price: 310 },
    { cat: "space", name: "Space Station Hub", icon: "🛸🏢", img: "assets/stickers/space_station_hub.jpg", rarity: "Epic", price: 510 },

    // Sweets & Treats (65 items)
    { cat: "sweets", name: "Royal Honey Sundae", icon: "🍨👑", img: "assets/stickers/royal_honey_sundae.jpg", rarity: "Legendary", price: 600 },
    { cat: "sweets", name: "Triple Tier Cake", icon: "🎂✨", img: "assets/stickers/triple_tier_cake.jpg", rarity: "Legendary", price: 580 },
    { cat: "sweets", name: "Rainbow Boba Blast", icon: "🧋🌈", img: "assets/stickers/rainbow_boba.jpg", rarity: "Epic", price: 530 },
    { cat: "sweets", name: "Golden Honey Waffle", icon: "🧇🍯", img: "assets/stickers/golden_honey_waffle.jpg", rarity: "Epic", price: 510 },
    { cat: "sweets", name: "Glazed Galaxy Donut", icon: "🍩🌌", img: "assets/stickers/glazed_galaxy_donut.jpg", rarity: "Epic", price: 500 },
    { cat: "sweets", name: "Strawberry Shortcake", icon: "🍰🍓", img: "assets/stickers/strawberry_shortcake.jpg", rarity: "Epic", price: 490 },
    { cat: "sweets", name: "Chocolate Lava Cake", icon: "🍫🌋", img: "assets/stickers/chocolate_lava_cake.jpg", rarity: "Epic", price: 520 },
    { cat: "sweets", name: "Pancake Tower with Syrup", icon: "🥞🍯", img: "assets/stickers/pancake_tower_with_syrup.jpg", rarity: "Rare", price: 430 },
    { cat: "sweets", name: "Frosted Cupcake", icon: "🧁💖", img: "assets/stickers/frosted_cupcake.jpg", rarity: "Rare", price: 410 },
    { cat: "sweets", name: "Caramel Macaron", icon: "🥯✨", img: "assets/stickers/caramel_macaron.jpg", rarity: "Rare", price: 400 },
    { cat: "sweets", name: "Ice Cream Swirl Cone", icon: "🍦", rarity: "Rare", price: 390 },
    { cat: "sweets", name: "Gummy Bear Rainbow", icon: "🧸🍬", img: "assets/stickers/gummy_bear_rainbow.jpg", rarity: "Rare", price: 420 },
    { cat: "sweets", name: "Choco Chip Cookie", icon: "🍪", rarity: "Common", price: 300 },
    { cat: "sweets", name: "Sweet Lollipop", icon: "🍭", rarity: "Common", price: 300 },
    { cat: "sweets", name: "Wrapped Candy", icon: "🍬", rarity: "Common", price: 300 },
    { cat: "sweets", name: "Fresh Strawberry", icon: "🍓", rarity: "Common", price: 310 },
    { cat: "sweets", name: "Juicy Watermelon", icon: "🍉", rarity: "Common", price: 310 },
    { cat: "sweets", name: "Crisp Red Apple", icon: "🍎", rarity: "Common", price: 300 },
    { cat: "sweets", name: "Sweet Peach", icon: "🍑", rarity: "Common", price: 320 },
    { cat: "sweets", name: "Butter Croissant", icon: "🥐", rarity: "Common", price: 330 },
    { cat: "sweets", name: "Pretzel Twist", icon: "🥨", rarity: "Common", price: 310 },
    { cat: "sweets", name: "Hot Popcorn Bucket", icon: "🍿", rarity: "Common", price: 320 },

    // Magic & Fantasy (60 items)
    { cat: "fantasy", name: "Magic Crystal Dragon", icon: "🐉💎", img: "assets/stickers/magic_crystal_dragon.jpg", rarity: "Legendary", price: 600 },
    { cat: "fantasy", name: "Fire Dragon Lord", icon: "🐉🔥", img: "assets/stickers/fire_dragon_lord.jpg", rarity: "Legendary", price: 600 },
    { cat: "fantasy", name: "Phoenix Reborn", icon: "🦅🔥", img: "assets/stickers/phoenix_reborn.jpg", rarity: "Legendary", price: 600 },
    { cat: "fantasy", name: "Enchanted Castle", icon: "🏰✨", img: "assets/stickers/enchanted_castle.jpg", rarity: "Legendary", price: 590 },
    { cat: "fantasy", name: "Mermaid Princess", icon: "🧜‍♀️🌊", img: "assets/stickers/mermaid_princess.jpg", rarity: "Epic", price: 540 },
    { cat: "fantasy", name: "Crystal Wizard Wand", icon: "🪄💎", rarity: "Epic", price: 510 },
    { cat: "fantasy", name: "Golden Treasure Chest", icon: "🪙💎", rarity: "Epic", price: 530 },
    { cat: "fantasy", name: "Mystic Spellbook", icon: "📖✨", img: "assets/stickers/mystic_spellbook.jpg", rarity: "Epic", price: 500 },
    { cat: "fantasy", name: "Knight in Shining Armor", icon: "🛡️⚔️", img: "assets/stickers/knight_in_shining_armor.jpg", rarity: "Epic", price: 490 },
    { cat: "fantasy", name: "Magic Potion Cauldron", icon: "🧪🔮", img: "assets/stickers/magic_potion_cauldron.jpg", rarity: "Rare", price: 440 },
    { cat: "fantasy", name: "Crystal Ball of Truth", icon: "🔮✨", img: "assets/stickers/crystal_ball_of_truth.jpg", rarity: "Rare", price: 430 },
    { cat: "fantasy", name: "Glowing Fairy Wings", icon: "🧚‍♀️💖", img: "assets/stickers/glowing_fairy_wings.jpg", rarity: "Rare", price: 450 },
    { cat: "fantasy", name: "Golden Crown of Kings", icon: "👑✨", img: "assets/stickers/golden_crown_of_kings.jpg", rarity: "Rare", price: 420 },
    { cat: "fantasy", name: "Heroic Shield", icon: "🛡️", rarity: "Common", price: 330 },
    { cat: "fantasy", name: "Magic Wand", icon: "🪄", rarity: "Common", price: 310 },
    { cat: "fantasy", name: "Gemstone Ruby", icon: "💎", rarity: "Common", price: 320 },
    { cat: "fantasy", name: "Ancient Parchment", icon: "📜", rarity: "Common", price: 300 },
    { cat: "fantasy", name: "Dungeon Key", icon: "🗝️", rarity: "Common", price: 310 },
    { cat: "fantasy", name: "Campfire Flame", icon: "🔥", rarity: "Common", price: 300 },

    // Sports & Hobbies (55 items)
    { cat: "sports", name: "Golden World Cup Trophy", icon: "🏆🌟", img: "assets/stickers/golden_world_cup_trophy.jpg", rarity: "Legendary", price: 600 },
    { cat: "sports", name: "Grand Piano Maestro", icon: "🎹🎶", img: "assets/stickers/grand_piano_maestro.jpg", rarity: "Legendary", price: 580 },
    { cat: "sports", name: "Rockstar Electric Guitar", icon: "🎸⚡", img: "assets/stickers/rockstar_electric_guitar.jpg", rarity: "Epic", price: 530 },
    { cat: "sports", name: "Pro Gaming Setup", icon: "🎮🎧", img: "assets/stickers/pro_gaming_setup.jpg", rarity: "Epic", price: 520 },
    { cat: "sports", name: "Master Artist Palette", icon: "🎨🖌️", img: "assets/stickers/master_artist_palette.jpg", rarity: "Epic", price: 500 },
    { cat: "sports", name: "Karate Black Belt", icon: "🥋🥋", img: "assets/stickers/karate_black_belt.jpg", rarity: "Epic", price: 490 },
    { cat: "sports", name: "Golden Medal 1st Place", icon: "🥇⭐", rarity: "Rare", price: 440 },
    { cat: "sports", name: "Slam Dunk Basketball", icon: "🏀🔥", img: "assets/stickers/slam_dunk_basketball.jpg", rarity: "Rare", price: 410 },
    { cat: "sports", name: "Bicycle Champion", icon: "🚴💨", img: "assets/stickers/bicycle_champion.jpg", rarity: "Rare", price: 420 },
    { cat: "sports", name: "Skateboard Kickflip", icon: "🛹💨", img: "assets/stickers/skateboard_kickflip.jpg", rarity: "Rare", price: 400 },
    { cat: "sports", name: "Soccer Ball Goal", icon: "⚽🥅", img: "assets/stickers/soccer_ball_goal.jpg", rarity: "Common", price: 330 },
    { cat: "sports", name: "Baseball Home Run", icon: "⚾", rarity: "Common", price: 310 },
    { cat: "sports", name: "Tennis Ace", icon: "🎾", rarity: "Common", price: 310 },
    { cat: "sports", name: "Bowling Strike", icon: "🎳", rarity: "Common", price: 320 },
    { cat: "sports", name: "Photography Camera", icon: "📷", rarity: "Common", price: 340 },
    { cat: "sports", name: "Headphones Beats", icon: "🎧", rarity: "Common", price: 330 },

    // Nature & Wonders (60 items)
    { cat: "nature", name: "Erupting Volcano", icon: "🌋🔥", img: "assets/stickers/erupting_volcano.jpg", rarity: "Legendary", price: 600 },
    { cat: "nature", name: "Aurora Borealis Northern Lights", icon: "🌌💚", img: "assets/stickers/aurora_borealis_northern_lights.jpg", rarity: "Legendary", price: 600 },
    { cat: "nature", name: "Great Coral Reef", icon: "🪸🐠", rarity: "Legendary", price: 580 },
    { cat: "nature", name: "Giant Redwood Tree", icon: "🌲✨", img: "assets/stickers/giant_redwood_tree.jpg", rarity: "Epic", price: 510 },
    { cat: "nature", name: "Rainbow Mountain", icon: "🏔️🌈", img: "assets/stickers/rainbow_mountain.jpg", rarity: "Epic", price: 530 },
    { cat: "nature", name: "Mighty Waterfall", icon: "🌊🏞️", img: "assets/stickers/mighty_waterfall.jpg", rarity: "Epic", price: 500 },
    { cat: "nature", name: "Golden Sunflower Meadow", icon: "🌻☀️", img: "assets/stickers/golden_sunflower_meadow.jpg", rarity: "Rare", price: 430 },
    { cat: "nature", name: "Desert Blooming Cactus", icon: "🌵🌸", img: "assets/stickers/desert_blooming_cactus.jpg", rarity: "Rare", price: 410 },
    { cat: "nature", name: "Tropical Palm Island", icon: "🏝️🥥", img: "assets/stickers/tropical_palm_island.jpg", rarity: "Rare", price: 420 },
    { cat: "nature", name: "Snowy Mountain Peak", icon: "🏔️❄️", img: "assets/stickers/snowy_mountain_peak.jpg", rarity: "Rare", price: 400 },
    { cat: "nature", name: "Four-Leaf Clover", icon: "🍀", rarity: "Common", price: 320 },
    { cat: "nature", name: "Cherry Blossom Bloom", icon: "🌸", rarity: "Common", price: 310 },
    { cat: "nature", name: "Red Rose", icon: "🌹", rarity: "Common", price: 300 },
    { cat: "nature", name: "Maple Leaf", icon: "🍁", rarity: "Common", price: 300 },
    { cat: "nature", name: "Pine Tree", icon: "🌲", rarity: "Common", price: 300 },
    { cat: "nature", name: "Raindrop Splash", icon: "💧", rarity: "Common", price: 300 },
    { cat: "nature", name: "Bright Sunbeam", icon: "☀️", rarity: "Common", price: 310 },
    { cat: "nature", name: "Rainbow Sky", icon: "🌈", rarity: "Common", price: 340 },

    // Science & Superstars (60 items)
    { cat: "superstars", name: "Quantum Computer Core", icon: "💻⚡", img: "assets/stickers/quantum_computer_core.jpg", rarity: "Legendary", price: 600 },
    { cat: "superstars", name: "Einstein Genius Brain", icon: "🧠💡", img: "assets/stickers/einstein_genius_brain.jpg", rarity: "Legendary", price: 600 },
    { cat: "superstars", name: "Friendly AI Robot", icon: "🤖💖", img: "assets/stickers/friendly_ai_robot.jpg", rarity: "Legendary", price: 590 },
    { cat: "superstars", name: "DNA Double Helix", icon: "🧬✨", img: "assets/stickers/dna_double_helix.jpg", rarity: "Epic", price: 530 },
    { cat: "superstars", name: "High-Power Microscope", icon: "🔬🔍", img: "assets/stickers/high_power_microscope.jpg", rarity: "Epic", price: 510 },
    { cat: "superstars", name: "Genius Scientist Flask", icon: "🧪🟢", img: "assets/stickers/genius_scientist_flask.jpg", rarity: "Epic", price: 490 },
    { cat: "superstars", name: "Graduation Honor Cap", icon: "🎓📜", img: "assets/stickers/graduation_honor_cap.jpg", rarity: "Epic", price: 520 },
    { cat: "superstars", name: "Atom Molecule Model", icon: "⚛️💫", img: "assets/stickers/atom_molecule_model.jpg", rarity: "Rare", price: 440 },
    { cat: "superstars", name: "Electric Tesla Coil", icon: "⚡🔋", img: "assets/stickers/electric_tesla_coil.jpg", rarity: "Rare", price: 420 },
    { cat: "superstars", name: "Smart Laptop", icon: "💻", rarity: "Rare", price: 400 },
    { cat: "superstars", name: "Glowing Lightbulb Idea", icon: "💡", rarity: "Common", price: 320 },
    { cat: "superstars", name: "Magnet Field", icon: "🧲", rarity: "Common", price: 310 },
    { cat: "superstars", name: "Laboratory Flask", icon: "🧪", rarity: "Common", price: 310 },
    { cat: "superstars", name: "Magnifying Glass", icon: "🔍", rarity: "Common", price: 300 },
    { cat: "superstars", name: "Golden Trophy", icon: "🏆", rarity: "Common", price: 350 },
    { cat: "superstars", name: "Gold Ribbon", icon: "🎖️", rarity: "Common", price: 320 }
];

// Build 100% unique collectible sticker catalog sorted from lowest value to highest value
const ALL_STICKERS = RAW_STICKER_SEEDS
    .slice()
    .sort((a, b) => a.price - b.price || a.name.localeCompare(b.name))
    .map((seed, idx) => ({
        id: idx + 1,
        name: seed.name,
        category: seed.cat,
        icon: seed.icon,
        img: seed.img || null,
        rarity: seed.rarity,
        price: seed.price
    }));
